#!/bin/bash
set -efu

cd $AUTOPKGTEST_TMP

# only float and double are available on all platforms
fftwf-wisdom -n -o wisdom cof1024 cob1024 r4096
fftw-wisdom-to-conf < wisdom > conf.c

fftw-wisdom -n -o wisdom cof1024 cob1024 r4096
fftw-wisdom-to-conf < wisdom > conf.c
